
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: stable-charts   # You can keep the name the same or rename it if desired
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.bitnami.com/bitnami

