
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: stable-charts  # We are using the Bitnami Helm repository
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.bitnami.com/bitnami

