
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: default
spec:
  releaseName: nginx
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: stable-charts  # This points to the Bitnami repo now
        namespace: flux-system
  values:
    service:
      type: LoadBalancer

