
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: default
spec:
  releaseName: nginx
  chart:
    spec:
      chart: nginx
      version: "18.2.2"  # Using the latest version of Nginx from Bitnami
      sourceRef:
        kind: HelmRepository
        name: stable-charts  # Ensure this matches your HelmRepository name
        namespace: flux-system
  interval: 5m
  values:
    service:
      type: LoadBalancer

