
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: default
spec:
  releaseName: nginx
  chart:
    spec:
      chart: nginx
      version: "1.0.0"  # Example version
      sourceRef:
        kind: HelmRepository
        name: stable-charts
        namespace: flux-system
  values:
    service:
      type: LoadBalancer
